AzureAD/microsoft-authentication-library-for-python

msal/application.py, msal/oauth2cli/assertion.py, msal/oauth2cli/authcode.py, msal/oauth2cli/oauth2.py, msal/token_cache.py, msal/wstrust_request.py, tests/test_client.py
This PR is a superset of existing PR #11.
~The major part is equivalent, but here it is done the otherway around, i.e. `b"." in data_in_bytes` rather than `"." in data_in_bytes.decode()`. This way we deal with `bytes` directly, and save an ad-hoc type conversion. (On a side note, another alternative is to normalize the input into `string` at the very beginning and keep it, that would bring some handy benefit when later we want to log it. But the major drawback is the underlying requests library is technically [expecting bytes (per their documentation)](http://docs.python-requests.org/en/master/api/#requests.request), and actually [converting strings into bytes under the hood](https://github.com/requests/requests/blob/v2.21.0/requests/models.py#L103-L104). So normalizing-to-string would be …
=> Assertion in bytes in python3

msal/application.py, msal/authority.py, tests/test_authority.py
This PR resolves issue #15.
How to test?
* Use MSAL Python 0.1.0. Start fiddler. Add a `verify=False` flag in any of the samples. Run it. You won't be able to complete a sample run due to the library complaining (this is essentially a Man-in-the-middle attack).
* You can test this PR by:
pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@full-support-for-verify-and-proxies
* Rerun the previous test. This time you will successfully obtain a token (despite some warning message emitted from underlying library).
=> Full support for verify and proxies

msal/application.py, msal/token_cache.py, sample/client_credential_sample.py, sample/device_flow_sample.py, sample/username_password_sample.py, tests/test_token_cache.py
* Change scope's internal representation from a list to a string
* Remove client_info from RefreshToken because it was optional and now obsolete
* Add test case to ensure the token cache representation complies with the Unified Schema
* The existing token cache implementation is already extendable, we only need to add a test case to assert that.
You can install this branch for your testing:
pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@target-in-string
=> Adjusting token cache format

msal/token_cache.py, tests/test_token_cache.py
This fixes one of the issues we found in yesterday's testing session. @MarkZuber @abhidnya13
=> Fix bug of cache.has_state_changed not being initialized

README.md
Add an early link to the recently-revised [other ADAL or MSAL SDKs page](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Microsoft-Authentication-Client-Libraries), as inspired by the same thing [Kusto Python library did](https://github.com/Azure/azure-kusto-python/blob/master/README.md#looking-for-sdks-for-other-languagesplatforms). (They are another first party internal customer who takes dependency of ADAL Python, by the way.)
Also reorganize the sample links a little bit.
Consider this PR is part of the April effort of refining our docs before the Build.
=> Add an early link to other ADAL or MSAL SDKs

msal/application.py, msal/wstrust_request.py, sample/username_password_sample.py
By refering to [a newly created wiki page here about the Username Password Authentication constraints](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication), this PR will close #33 by addressing all 3 action items mentioned in its comment: the API reference doc, the sample, and the exception output.
=> Improve supportability for Username Password Flow

msal/application.py
- Client assertion type was not set in configuration of client for certificate credential flow. 
- This PR adds the client assertion type.
=> Adding client assertion type

msal/application.py
Merge the release 0.3.1 branch back to dev branch.
=> MSAL Python 0.3.1

msal/application.py, msal/token_cache.py, tests/test_application.py
Add remove_account() API, and it will signout the account from the app family. This PR will close #12 .
Most of the implementations are refactoring the underlying cache helpers. To review high level "what does it do" logic, please focus on only 50 lines starting from [here](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/41/files#diff-f7ae931bcdab4b14f3a256baf7d6922aR283) (half of them are inline documentation).
=> Add remove_account() API

msal/token_cache.py, tests/test_token_cache.py
In this PR, we adjust to not write null into token cache. Relevant test case is also updated.
=> Do not write null into family_id

sample/authorization-code-flow-sample/authorization_code_flow_sample.py
Even this is just a sample app, not our production library code, we are still making this improvement as precaution.
In such flask-based sample, a secret key is needed for its session feature to function. [Flask's own official documentation does it all the time](http://flask.pocoo.org/docs/1.0/quickstart/#sessions).
Nonetheless, we now avoid hardcoding secret, not even a placeholder.
=> Avoid hardcoding secret

msal/token_cache.py
If `response["expires_in"]` is a string--as is the case for [Azure Instance Metadata Service](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http) auth responses--lines 142 and 144 will raise because strings and integers can't be added. This change ensures all addends (`now`, `expires_in`, `ext_expires_in`) are integers.
This also fixes an issue with the access token key maker. It accepts an optional `client_id` but when this is unspecified, the key maker passes `None` to `str.join`, which raises. I changed this to pass the empty string instead, as do other key makers.
=> Handle string time values when caching responses

msal/authority.py, tests/test_authority.py
[Previous implementation](https://github.com/AzureAD/microsoft-authentication-library-for-python/blame/dev/msal/authority.py#L41) was based on some hallway communication 3 years ago. Sovereign scenario was not brought up at that time, and such implementation happened to not work in sovereign scenarios.
PS: ADAL Python happened to use a different implementation which was not susceptible to this issue.
The actual fix is just a [one-liner](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/62/files#diff-cb217807c4296437af63bf4a2954b7b7R43). The rest are refactoring, notes and test cases adjustments.
@yugangw-msft , would you mind to test it by pulling it from this branch?
pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@sovere …
=> Support sovereign cloud.

msal/application.py
* Pass through verify flag
* change default value from None to [] as None leads to a crash further downstream
=> Pass through verify flag and fix scopes default value

msal/application.py
Discovered in PR #61 's second finding (thank you Jann!), the previous default None value in `acquire_token_by_username_password(..., scopes=None)` would cause an exception in our internal helper `decorate_scope()`.
The fix is to change the previously optional scopes parameter to required.
This kind of api surface change would usually be a breaking change, but in this case it is not,
because the previous default value would cause exception so it was in fact required.
FWIW, you can still explicitly use empty list `[]` as scope,
and the response would contain id_token and refresh_token, but no access_token.
=> Change an optional scopes parameter to be required

msal/application.py, msal/oauth2cli/assertion.py, tests/test_application.py
- This PR closes #60 
- Adds support for Subject Name Issuer Authentication which is to support cert auto rolls.
- We have tested the end to end scenario by creating our own Test Environment. We will work with the lab team for creating test environment and then integrating in Test automation.
- Note: 
This type of authentication expects authority url to be mentioned with the actual tenant id at the moment. Using organizations will fail the request
=> Subject Name and Issuer Authentication

msal/application.py, tests/test_assertion.py
This ~is a proof-of-concept in attempt to~ resolve #67.
~It has NOT been tested at this time.~ A unit test case is added.
Please also help proof-read [the documentation](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/68/files#diff-f7ae931bcdab4b14f3a256baf7d6922aR75), which will automatically be published into our [online reference doc](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.__init__) once this PR is merged.
@trwalke You do not have to look into the actual implementation, but please help double check with the [API surface](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/68/files#diff-f7ae931bcdab4b14f3a256baf7d6922aR96) and then [the new claim(s) would be sent inside client assertion (rather than, say, …
=> ConfidentialClient with extra claims

setup.py
It turns out [the approach we used in PR #69](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/69#discussion_r296942855) would cause the LICENSE being copied into `/usr/local`, which would typically end up with insufficient permission error while some downstream build pipeline (such as, OSX) attempts to install msal without explicitly specifying `--user` option.
This PR uses a different to pack that LICENSE file and ship it inside this library's directory.
=> Pack LICENSE in a different way

msal/application.py, setup.py
* This release is functionally identical to 0.5.0. We are just fixing a packaging issue (#74) which would potentially cause some installation difficulty on a certain platform(s). If MSAL Python 0.5.0 is already working fine for you, you do not need to upgrade.
=> Release 0.5.1

msal/oauth2cli/oidc.py
- This PR fixes the error that occurs in decoding token.
- The ID token is encoded as base64url, not base64.
- In the previous implementation, [device_flow_sample.py](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/device_flow_sample.py) will fails with error `binascii.Error: Incorrect padding`.
=> Use urlsafe_b64decode instead of b64decode

msal/token_cache.py
We already hide some most sensitive informatino before,
and PEN test team loves it.
This time we hide some extra information.
=> Refactor unittest logs

msal/application.py, tests/test_application.py, tests/test_e2e.py
What
-----
This PR will solve #53.
How was it implemented
--------------------------
While the actual implementation is technically a one-liner `return ...`, there are some design decisions documented as inline comments inside both the implementation and the test case. Review/feedbacks are welcome.
The configuration of test case is reused from [a similar test case in MSAL .Net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4.3.1/tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/OboTests.cs).
How the new API looks like
-----------------------------
This is the [updated API reference document](https://msal-python.readthedocs.io/en/obo/#msal.ConfidentialClientApplication.acquire_token_on_behalf_of), please also proofread.
How to install this …
=> On-behalf-of (OBO) Implementation

.travis.yml
[Python 3.8.0](https://www.python.org/downloads/release/python-380/) has been released yesterday. Now we include it in our test automation matrix.
=> Enable Python 3.8 in test automation

msal/application.py
Wire up and document the `get_authorization_request_url(..., response_type=...)` parameter.
It would be useful in scenario when a web app just want to acquire ID Token to sign in only.
=> Customizable response_type

msal/authority.py, tests/test_authority.py, tests/test_e2e.py
There is an automated test case in this PR to cover username password flow (i.e. ROPC grant), and it passes.
Currently, this implementation is still considered in an early stage. We can use it as a prototype to [work on some sample as proof-of-concept](https://github.com/Azure-Samples/ms-identity-python-webapp/pull/4), in order to get the whole picture of end-to-end experience of the "new" API surface and calling patterns. The interesting part of this PR, is something NOT in this PR: You will see this PR did NOT touch the source file `application.py` which contains current public API definition. That means, we keep the high level API surface unchanged for B2C and non-B2C scenarios.
We can install this branch by:
pip install git+https://github.com/AzureAD/microsoft-authentication-library-fo …
=> B2c implementation

sample/device_flow_sample.py
Since recently, the [Microsoft Identity platform supports Device Flow for personal accounts (MSA) too](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/728#issuecomment-527332063).
In this PR we adjust the comment, which is a mini-sample in its own to demonstrate "how to configure  this sample".
Manual test shows that:
* Using "common" endpoint can perform device flow to acquire a token for my corp account. So this change is at least as good as the previous "organizations" endpoint.
* Using "common" endpoint can also perform device flow for a Hotmail account. It seems the end user would need to type his/her password and redo the consent every time, though.
=> The more generic common endpoint can now support Device Flow for MSA

msal/authority.py
- Changing implementation to check for policy string format instead of b2clogin.com
- This supports custom domains with validateAuthority = True and sovereign clouds
=> Changing B2C implementation to verify policy format

msal/application.py
This will be useful in various web app scenarios.
~This PR is currently marked as draft, only because it is temporarily using another pending PR as its base. I'll change the base, right after that other PR gets merged.~
This PR is ready to be reviewed.
=> Support prompt parameter

sample/confidential_client_certificate_sample.py, sample/confidential_client_secret_sample.py
Backport https://github.com/Azure-Samples/ms-identity-python-daemon/pull/5
=> Sample json output

sample/confidential_client_certificate_sample.py, sample/confidential_client_secret_sample.py, sample/device_flow_sample.py, sample/username_password_sample.py
We were drafting this [logging wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Logging) and then realize that we could also add one more line per sample to demonstrate how to disable MSAL log while still enabling debug log for app dev's all other modules.
=> Demo how to disable MSAL log

setup.cfg
Per conversation in #115 , this PR will guide all future builds to produce a universal wheel.
=> Add setup.cfg to build universal wheel by default

msal/application.py
Release Notes:
There is no actual change between the previous 0.9.0 release and this release.
The major version number is bumped to have a 1.0.0 release. This indicates that the API surface in MSAL Python 1.0.0 is now stable and production ready. You may learn more about Versioning from [Semantic Versioning FAQ](https://semver.org/#how-do-i-know-when-to-release-100).
=> MSAL Python 1.0.0

README.md
@rayluo Please review. I wanted to add a badge for the CI build as well but couldn't find the CI build link for MSAL Python. Let me know as a comment if you have it.
=> Update Readme preview note and links

tests/test_e2e.py
This seems to be the only test case failing at the moment.
So we temporarily disable it, until we fix the test environment.
=> Disable OBO tests due to a temporary test environment issue

tests/test_e2e.py
The new test credential has been setup, and ready to use.
This PR basically reverts the previous workaround #131.
=> Re-enable OBO tests

tests/test_e2e.py
Quoted from LAB team notice:
> Beginning ~5th December 2019 at 9:00 am~ 9th December 2019 at 11:00 am PST, the scope of the Lab Confidential Client will change from "https://user.msidlab.com/.default" to "https://msidlab.com/.default"
* This PR is currently failing because the actual change has not happened yet.
* You will notice our test automation on OTHER branches start failing after ~Dec 5 2019 9AM PST~ the time mentioned above, and then this branch/PR will start to pass the test. That is the time you are going to merge this PR.
=> Lab API is switching to a new scope

msal/application.py, tests/test_e2e.py
~Resolves~ Addresses #130 <sub>Edited by Ray: Per the team-wide recent workflow, we have to avoid those magic keywords such as "resolves", in order to NOT close that issue until we actually release a new version containing this change.</sub>
For reference: The pattern MSAL Java uses is : 
```java
PublicClientApplication app = PublicClientApplication
.builder("client-id")
.correlationId("correlation-id")
.applicationName("app-name")
.applicationVersion("app-version")
.build();
```
The API this PR will implemented will be:
```python
pca = PublicClientApplication(
...,
app_name="my app",
app_version="1.2.3",
)
```
=> Adding app_name and app_version headers

msal/application.py, tests/test_application.py
Although empirically we saw `error_description` shows up in AAD response, it is an optional field, [per spec](https://tools.ietf.org/html/rfc6749#section-5.2).
In this PR, we adjust our implementation, to make it more robust.
=> error_description is optional

msal/application.py, tests/test_application.py
In an effort to address #57 , we need to expose some of the underlying token refreshing errors to app developer. After weighing different options (such as extending the existing `acquire_token_silent()` method with different style of opt-in flag: boolean, container, callback, ..., you name it), we chose to keep the original `acquire_token_silent()`'s behavior unchanged, and introduce a new `acquire_token_silent_with_error()` method.
The online documentation for both the old `acquire_token_silent()` and new `acquire_token_silent_with_error()` has also been updated and staged [here](https://msal-python.readthedocs.io/en/acquire_token_silent_with_error/#msal.ClientApplication.acquire_token_silent). Please also proofread.
Besides, quoted below is the upcoming Wiki page on how to use the new …
=> New method acquire_token_silent_with_error()

msal/authority.py
Adds openid as a parameter to allow for async authorities later.
Idea for async authority: Async authority will have a `async` `classmethod` that returns the `openid_config` and then it will use the default initializer of this class to pass it in. When implementing the async version, logic will be shared between the sync/async for if `openid_config is None`
=> take openid as parameter

docs/conf.py
conf.py imports the version from the local module, so it needs to have the
directory in the python path, otherwise it fails with:
$ sphinx-apidoc -f -e -o docs/api msal
Creating file docs/api/msal.application.rst.
Creating file docs/api/msal.authority.rst.
Creating file docs/api/msal.exceptions.rst.
Creating file docs/api/msal.mex.rst.
Creating file docs/api/msal.token_cache.rst.
Creating file docs/api/msal.wstrust_request.rst.
Creating file docs/api/msal.wstrust_response.rst.
Creating file docs/api/msal.rst.
Creating file docs/api/msal.oauth2cli.assertion.rst.
Creating file docs/api/msal.oauth2cli.authcode.rst.
Creating file docs/api/msal.oauth2cli.oauth2.rst.
Creating file docs/api/msal.oauth2cli.oidc.rst.
Creating file docs/api/msal.oauth2cli.rst.
Creating file docs/api/modules.rst.
$ …
=> Add source root dir to python path in docs/conf.py

msal/application.py, tests/test_e2e.py
The `nonce` is a behavior [defined in Open ID Connect](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
This PR adds a `nonce` parameter into the `get_authorization_request_url(..., nonce=...)` so that it would be sent to Azure AD.
This PR also adds a `nonce` parameter into the `acquire_token_by_authorization_code(..., nonce=...)` so that this method will perform the nonce check on the returned id token, automatically. We [test it here](https://github.com/AzureAD/microsoft-authentication-library-for-python/compare/nonce-in-msal?expand=1#diff-2f43f6151484c4ac714c0be06ac04a7cR141). By the way, [validating nonce has been embedded in msal .net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4.10.0/src/client/Microsoft.Identity.Client/Platforms/iO …
=> Specifying and validating nonce in auth code flow

tests/test_e2e.py
E2E Test Scenarios added:
- Acquire token by username password
- Acquire token by client_secret
- Acquire token by on behalf of flow
- Acquire token by device code flow
Besides, acquire token silent is tested in each of the flows individually (except acquire token by client secret)
=> Arlington automation

msal/application.py
Allows user to pass in domain hint when generating authorization URL
---
UPDATED (by Ray):
This PR will fix #158. (This line will trigger an automatic close of that issue. This is probably fine, because we will cut a new release shortly after this merge.)
=> Allow domain hint

msal/application.py, tests/test_application.py
=> Returning refresh token errors which were discarded

README.md, msal/authority.py
Today a customer was asking for our support on an error he encountered.
> I have registered my App on Azure Portal but hitting:
> `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
>
> when using:
>
> ```python
> auth = "https://login.microsoftonline.com/common/oauth2/nativeclient"
> app = PublicClientApplication(client_id, authority=auth)
> ```
And he further explained:
> I first went to this [MSAL repo's homepage](https://github.com/AzureAD/microsoft-authentication-library-for-python)
> there seems a bug in README (`config` was not defined but `config["scope"]` was called), so I went to [samples hosted inside same MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample)
Our takeaways:
* Customers expect code snippet in …
=> Improve error message on incorrect authority uri

msal/application.py, sample/migrate_rt.py
This PR implements the right-hand side of [this comparison](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/191#issuecomment-627640783). We can go with this direction, and then this PR will close #191.
The API calling pattern is largely the same as #191, if we do not really need to use its return value:
```python
app = msal.PublicClientApplication(
"client_id", ...)
result = app.acquire_token_by_refresh_token(
old_rt, ["scope1", "scope2"])
if "error" in result:
print(
"Error in Migration:",
json.dumps(result))
else:
print("Migration is successful")
```
There are still two higher level RT migration strategies:
+ One approach is to migrate RTs IN A BATCH within minutes, when a newer version of app (Azure CLI) is run for its first time on an end user's machine and …
=> acquire_token_by_refresh_token() for RT migration

README.md
I updated the example to match what the source seems to want.
=> One of the examples in the README was not legal python syntax.

msal/application.py, msal/authority.py, tests/test_application.py, tests/test_authority.py, tests/test_authority_patch.py
This reverts commit 8d62027c9067a05a4c4d482bf659e1411f2a37f2 i.e. #205 , which turns out breaks [Azure SDK's current monkeypatch](https://github.com/Azure/azure-sdk-for-python/blob/230afcfb50cea823d0fb23df75d740149ba5a503/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L135).
We now choose to revert this "lazy authority" feature, and then release a MSAL 1.4.1 asap, before existing Azure SDK customers hitting this. We will re-introduce the "lazy authority" feature at a later time, after Azure SDK's next release removing that monkeypatch.
=> Revert "Application initializer does not make tenant discovery calls (It was PR 205)"

msal/application.py, msal/authority.py, tests/test_application.py, tests/test_authority.py, tests/test_authority_patch.py
- Reverts Application Initializer will not send network requests introduced in MSAL Python 1.4.0 (#205, #216, #187)
=> MSAL Python 1.4.1

tests/test_e2e.py
List of client_ids changed:
- onprem ADFS2019 test cases - Using values from here : https://docs.msidlab.com/accounts/opadfsv2019.html
- OBO flow does not have a query exposed yet so storing the client ids as environment variables for now
- B2C test cases - Using values from https://msidlab.com/api/App?azureenvironment=azureb2ccloud
Fixes #180
=> Removing hardcoded client_ids from test environment

msal/application.py
As this method was added after #103 was merged, we did not add telemetry data for this API
Adding it in this PR.
TO DO: Update [this](https://microsoft-my.sharepoint-df.com/:x:/p/sagonzal/EXSrr4vM1utAqQQfD6bMln4BYKwjrqh3cagiNJWPVNjLzw?e=j8wQ9e) doc when the PR is merged
=> Adding telemetry id for acquire_token_by_refresh_token

msal/mex.py
Closes #226 
- Content-type is not needed for Http GET requests
- Verified its not used in [MSAL .NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs#L34) implementation or [MSAL Java](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/ca87b927f249f7dd00bb422be255137409cbe492/src/main/java/com/microsoft/aad/msal4j/WSTrustRequest.java#L80) implementation.
=> Removing content type header for GET requests to Mex endpoint

msal/application.py, tests/test_e2e.py
This PR adds a test case to reproduce the error found in #223. It is expected to fail right now.
=> Adding test case for acquire_token_silent in Arlington

msal/application.py, tests/test_application.py
Found an issue introduced in #225. This PR fixes that, and will close #235
=> Do not filter mrrt by scope

msal/application.py
* Bugfix: A regression in previous release causing MSAL to not able to read some tokens from a different authority alias (#235, #236)
=> MSAL Python 1.4.3

msal/application.py, tests/test_application.py
- Removing an extra period
- Using `foo` and `bar` as mock client capability values to avoid confusion for developers.
=> Changes in client capabilities as per AzCLI feedback

msal/application.py, msal/authority.py, msal/mex.py, tests/test_application.py
- Added support for setting [client capabilities](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Client-capabilities) to enable CAE(Continuous Access Evaluation) (#240, #174)
- Device code endpoint is now fetched from open-id configuration, if available. (#245, #242)
- Fixes in test cases (#239, #211)
=> MSAL Python 1.5.0

msal/application.py, msal/token_cache.py
@abhidnya13 please help verify this, both by re-running our BF/FF manual tests, and by code review, to see whether this can address the issue we found recently.
=> Cache tokens by specified environment, not by OIDC Discovery

msal/application.py
After our recent change in ADAL Python : https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/240, 
I'm adding such a default in MSAL Python too. 
Let me know your thoughts.
=> Adding default value for cloud audience urn extracted from User Realm Response

msal/application.py, msal/oauth2cli/oauth2.py, msal/token_cache.py
=> Do not add account when performing acquire_token_silent()

msal/application.py, msal/authority.py, tests/test_application.py
* Bugfix: We now cache tokens by specified environment, not by OIDC Discovery. This won't matter most of the time, but it can be needed when your tenant is in transitional state while migrating to a different cloud. (#247)
* Bugfix: We now make sure one app's sign-out operation would be successful even when another app is acquiring token from cache at the same time. (#258, #262)
=> Release 1.5.1

msal/authority.py
This can likely close #263 .
@AlmogBentz You can install this branch for your smoke testing:
pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@differentiate-oidc-discovery-errors
After this patch, when the lower level network-relevant error (came from requests) occurs, they would be bubbled up as-is, therefore you won't see the "Authority would typically be in a format of ..." error message. You could catch them and treat them differently, therefore satisfying your desire to handle different exception differently.
=> Bubble http exceptions so apps could catch them

msal/application.py, setup.py, tests/test_application.py
Usage: We add one more optional field `passphrase` in the existing `client_credential` parameter of `ConfidentialClientApplication`. The docs will also be updated [here](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/270/files#diff-4d32d284fa6acf43894719eff11cb366e5969e0b61593bfd00c68a4cf9c441caR125-R136)
=> Passing encrypted key as credential

msal/token_cache.py, tests/test_token_cache.py
=> Reuse old rt data even if its key is different

msal/application.py, msal/oauth2cli/oauth2.py, msal/oauth2cli/oidc.py, tests/test_e2e.py
This PR implements the recent new API proposal (its [internal link here](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/2272)). It will become the foundation of the upcoming Interactive flow feature.
The new API `initiate_auth_code_flow()` and `acquire_token_by_auth_code_flow()` also provide PKCE support automatically, without needing the app developer to provide any PKCE-relevant parameters, so that different app developers would not hit [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/42906) any more. This PR will close #255.
Inline-documentation and end-to-end test cases are included. Docs will soon be available at https://msal-python.readthedocs.io/en/latest/
I'll also provide [a corresponding PR in our web app sample repo, to …
=> New initialize_auth_code_flow() and acquire_token_by_auth_code_flow()

msal/application.py, tests/test_e2e.py
Original goal:
- Adding state ~and pkce~
- ~Can we use a custom browser~
- Cleaning up the code and structure
- Reference docs
---
Latest Update:
The latest commit implements:
- `state`, `nonce` and `PKCE` protection are already implemented by recent refactoring. This PR is built on top of that, thus including these security behavior. This PR focus on the new `acquire_token_interactive()` API.
- Reference docs is available [in staging environment](https://msal-python.readthedocs.io/en/docs-staging/#msal.PublicClientApplication.acquire_token_interactive), and will show up [in production](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.acquire_token_interactive) once this PR is merged.
- Telemetry with API ID (the new API ID is also updated into the [internal …
=> Acquire token interactive  using system browser

msal/application.py, tests/http_client.py
While working on a sample to demonstrate the newly-merged #260, we found a malfunction which prevented `acquire_token_interactive()` from functioning. So, a follow-up question would be, why the existing test automation did not catch that. Further investigation shows that, our previous test HttpClient was overly-flexible. Now both issues are fixed.
I'll commit the new sample in a different PR (so that it will be cleaner to be referenced).
=> Fix a malfunction in yesterday's acquire_token_interactive() PR

msal/application.py
=> Enables extra_scopes_to_consent in acquire_token_silent()

msal/application.py
* New feature: A new `extra_scopes_to_consent` parameter is introduced to the `acquire_token_interactive(...)` API (#212, #286)
* Adjustment to previous version 1.7.0: Lazy import `webbrowser` module only when necessary (#287, #288)
=> Release 1.8.0

msal/oauth2cli/assertion.py, msal/oauth2cli/oauth2.py, setup.py
=> Compatible with pyjwt1 and 2

msal/application.py, tests/test_e2e.py
Refactor SSH Cert test cases to represent test requirements, and officially support SSH Cert for SP.
=> Ssh cert tests

msal/application.py
Fix #301 by changing the deprecation warning message to:
```
msal/application.py:446: DeprecationWarning: Change your get_authorization_request_url() to initiate_auth_code_flow()
msal/application.py:581: DeprecationWarning: Change your acquire_token_by_authorization_code() to acquire_token_by_auth_code_flow()
```
@chlowell Does those wording work for you?
=> Precise DeprecationWarning for auth code API

msal/application.py
- Pass `kwargs` to `ClientApplication.acquire_token_by_refresh_token` so that `data` can be passed to `Client.obtain_token_by_refresh_token`.
- Call `_validate_ssh_cert_input_data` to make sure `data` is valid.
=> Pass kwargs to acquire_token_by_refresh_token

msal/oauth2cli/oidc.py
=> Improve aud error msg

sample/confidential_client_certificate_sample.py, sample/confidential_client_secret_sample.py, sample/device_flow_sample.py, sample/interactive_sample.py, sample/migrate_rt.py, sample/username_password_sample.py
More suitable for work :-)
CC: @tonybaloney
=> ReadTheDocs, not RTFD

msal/application.py, tests/test_application.py
Per discussion with our customer, it is decided to filter out the `refresh_in` information from MSAL's response, because MSAL already implements the Proactive Refresh accordingly, so our customers do not need to see the `refresh_in` value, thus avoid potentially confusing it with the `expires_in`. CC: @chlowell
=> Filter out refresh_in from auth responses

msal/application.py
`scope` -> `scopes` to follow the function signature:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/888559355436383c900940713edd21763bb2141d/msal/application.py#L314
=> Fix typos in docstring

msal/application.py
The previous behavior is [the default behavior in requests, which does not retry at all](https://github.com/psf/requests/blob/v2.25.1/requests/adapters.py#L94-L108). Here we enable one retry. Too many retries could cause the application to hang for longer.
@jiasli What do you think?
=> Enable retry on connection error

msal/application.py, msal/telemetry.py, msal/token_cache.py, tests/test_application.py
This PR will close #137 and also close #175
=> Implementing Telemetry V4

msal/wstrust_response.py
This [ADAL issue 250](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/250) also exists in MSAL. This PR fixes it in MSAL.
=> Saml token should use utf-8 encoding

msal/application.py
PyCharm gives warning for the incorrect type hint:
=> Fix type hint for `client_credential`

msal/application.py, sample/username_password_sample.py, tests/test_e2e.py
This resolves #294 .
This PR does the following things:
* Move ROPC from `PublicClientApplication` to its base, so that `ConfidentialClientApplication` would also have this feature
* Adding end-to-end test cases
* Also changes the built-in sample accordingly
=> Add ROPC support to Confidential Client

msal/application.py, tests/test_application.py
This way, the caller of `get_accounts(...)` (which is typically downstream application's account picker) would no longer need to choose among multiple equivalent accounts. This change is functionally equivalent in terms of the subsequent `acquire_token_silent(..., account=account)` call.
CC: @jiasli @chlowell
=> get_accounts() will group equivalent accounts and return the merged result

docs/index.rst
This addresses a [side effect](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/319/files#r609100105) of #319.
=> Bring back docs for __init__()

msal/__init__.py, msal/oauth2cli/oidc.py, sample/interactive_sample.py
By design, MSAL Python's `acquire_token_interactive(..., prompt=...)` always accepts arbitrary string, so this feature has already been shipped last year.
This PR adds a line in the dev sample to show how to use it.
This PR is now the last action item of #356 , so, it will resolve #356.
=> A demo on how to use prompt=create

msal/application.py, msal/region.py, setup.py, tests/test_e2e.py
This resolves #295.
Feature wise this is completed.
~~TODO: Currently the authority validation is still performed. Would need to decide whether that is desirable. CC: @bgavrilMS~~ Now MSAL will ignore connection error during Authority Validation if app developer opted in to use `azure_region`.
=> Reginal endpoint support

msal/application.py, msal/token_cache.py, tests/test_e2e.py
This PR implements the [internal proposal](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/3310), and the finished product will resolve #207 in MSAL Python.
There are currently 3 commits in this PR.
* The last commit is for the API interface adjustment.
* The first commit is to relax some test cases to allow the absence of a RT. That is it. The MSAL Python core needs no specific change to operate without a RT.
* The second commit is to implement the optional appendix 2 in the internal proposal.
=> Remove offline access

msal/application.py
To reproduce the error:
```py
from msal import PublicClientApplication
class Client:
def get(*args, **kwargs):
raise Exception('oops')
PublicClientApplication('...', http_client=Client())
```
```
Traceback (most recent call last):
File "repro.py", line 8, in <module>
PublicClientApplication("...", http_client=Client())
File "...lib\site-packages\msal\application.py", line 1296, in __init__
super(PublicClientApplication, self).__init__(
File "...lib\site-packages\msal\application.py", line 302, in __init__
if validate_authority and region:
NameError: name 'region' is not defined
```
I assume the keyword argument `azure_region` is intended.
=> Fix NameError in ClientApplication exception handler

msal/application.py, sample/vault_jwt_sample.py, tests/test_client.py, tests/test_e2e.py
JWT.
Useful for where the signing takes place externally for example using
Azure Key Vault (AKV).
AKV sample included.
This is the MSAL version of [This pull](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/196)
=> Add support for acquiring a token with a pre-signed JWT

msal/application.py
This would handle some of the symptoms in #372 , but this PR alone won't change the minutes-long latency when using region endpoint from outside if Azure VM.
=> Skip unnecessary and repetitive region detection

README.md, msal/application.py, sample/vault_jwt_sample.py, tests/test_client.py, tests/test_e2e.py
* New feature: MSAL supports a confidential client being authenticated by a pre-signed assertion. Usage:
```python
cca = ConfidentialClientApplication(
...,
client_credential={"client_assertion": "...a JWT with claims aud, exp, iss, jti, nbf, and sub..."},
...)
```
This can be useful for where the signing takes place externally for example using Azure Key Vault (AKV).
AKV sample included (#161, #271).
* Improvement: Skip unnecessary and repetitive region detection. (#372, #373)
=> Release 1.13.0

msal/token_cache.py
For some reason, the response data would be slightly different. This change can tolerate that variation, and fix #387.
Hi @letmaik , since we can not reproduce this issue with our test account here, we would need your help to verify its fix. Can you install a special MSAL by the following command line, and then re-run your application?
pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@fix-issue-387
=> Handle different response outcome

msal/application.py, msal/region.py, tests/test_e2e.py
The previous regional endpoint behavior implemented in #358 would receive some changes defined in [this internal memo](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/3768). In particular, the removal of `REGION_NAME` usage would also close #382.
=> Changing region endpoint, and remove usage of REGION_NAME env var

msal/application.py
Edge will soon become the first browser on Linux to support device-based conditional access policy. This PR has MSAL to prefer using Edge for `acquire_token_interactive()`.
How to test this feature?
1. Install this feature branch by `pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@prefer-edge-on-linux`.
2. Download the out-of-the-box [interactive sample](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.13.0/sample/interactive_sample.py)
3. Prepare a config.json file with content like this, and then run `python interactive_sample.py config.json`:
```json
{
"authority": "https://login.microsoftonline.com/common",
"client_id": "289a413d-284b-4303-9c79-94380abe5d22",
"scope": ["User.Read"],
"endpoint": …
```
=> Prefer Edge when running on Linux

msal/application.py, msal/individual_cache.py, msal/throttled_http_client.py, tests/test_individual_cache.py, tests/test_throttled_http_client.py
It is the cache behavior on http layer. Such a cache is used internally to cache some http responses for performance optimization. In particular, when such an optimization happens on http 429/5xx with Retry-After header, it is a protection also known as "throttling" in MSAL parlance. This behavior resolves #159.
Such an http cache behavior is always enabled. Currently, the http cache is in-memory only.
=> Http cache

msal/application.py, tests/test_ccs.py, tests/test_e2e.py
The implementation is based on a follow-up conversation in this [internal design PR](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/3304). This PR will resolve #376.
=> Implementing CCS Routing info

msal/oauth2cli/authcode.py, msal/oauth2cli/oauth2.py
This PR fix #393 which only happens on Windows.
=> Allow interactive flow to be aborted by CTRL+C even when running on Windows

msal/application.py, msal/oauth2cli/oidc.py
Per [internal discussion](https://stackoverflow.microsoft.com/questions/267209), we are implementing the `max_age` feature for both `ConfidentialClientApplication` and `PublicClientApplication`.
This PR will close #381.
=> Add max_age support

msal/application.py
Add this piece to also help resolve #376
=> Map login_hint into CCS routing info, too

msal/throttled_http_client.py, tests/test_throttled_http_client.py
When we worked on #379, we were already aware of the Device Authorization Flow (formerly known as Device Code Flow) would need a special treatment. And we attempted to address that in #379, but we made a mistake/bug. This PR fixes that bug, and resolves #408 .
=> Bypass device authorization flow, for real

setup.py
Even after this change, our CI/CD pipeline is still not yet picking up the latest cryptography 35.0.0, [not until our upstream dependency PyJWT also makes similar change](https://github.com/jpadilla/pyjwt/pull/691).
Thanks @beliaev-maksim and @graingert for bringing this to our attention.
This would close #411, close #413.
=> Bumping cryptography upper bound to X+3

msal/application.py
This will fix #431.
We won't have an easy way to test this. So, @jiasli please help the code review.
And, if the ConnectionError in Xing Zhuo's report is still observable, you can then pull in this feature branch and test it in rare real environment (by `pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@bubble-up-refresh-exception`).
=> Bubble up refresh exception when we cannot recover

msal/application.py, msal/authority.py, tests/http_client.py, tests/test_authority.py
The new usage pattern is documented in [our doc staging site (please search the keyword "authority (str)") in this page](https://msal-python.readthedocs.io/en/docs-staging/).
You can also try the new syntax by pulling its feature branch:
pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@cloud-instances
This is not a breaking change. The old school, low-level url string input is still supported.
This PR, once agreed upon and merged in, will resolve #221.
=> Define some Cloud Instance constants and the usage pattern of using them

msal/application.py
Based on conversation here https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/407#discussion_r727329068, we remove some unnecessary exceptions from the guidance.
=> Fine tune http_cache usage pattern

msal/authority.py
This is inspired from, and can also resolve https://github.com/Azure/azure-cli/issues/20507
=> Descriptive error messages for troubleshooting

msal/oauth2cli/oidc.py
This PR resolves #446 (Note: It turns out a PR can not automatically close a Discussion topic. I'll manually close it there.)
=> Actionable suggestion for ID token validation failures

msal/application.py, msal/wstrust_request.py
Inspired by https://github.com/Azure/azure-cli/issues/21068#issuecomment-1018752545 , this PR wraps most "expected" ADFS username password flow into one `RuntimeError` with actionable message.
That being said, this actionable message is meant for MSAL's app developer. If you are the app developer, you probably want to catch this `RuntimeError` and translate it into your own exception or error message, for example "... consider use 'az login' instead".  @jiasli
=> Actionable exception from ADFS username password flow

msal/application.py, msal/wstrust_request.py
@jiasli Azure CLI can then just catch all exceptions happened in `acquire_token_by_username_password()`, and then chain it with your CLIError:
```python
try:
app.acquire_token_by_username_password(...)
except Exception as ex:
raise CLIError('"az login -u ... -p ..." was unsuccessful. You may consider use "az login" instead.') from ex
```
=> Removes the middle-layer exception

.github/workflows/python-package.yml, setup.py
Adding more python3 versions into our test matrix.
* Python 3.10 is added and also declared in the classifier.
* Python 3.11 seems only available as a specific name, and the latest one is "3.11.0-alpha.5" currently.
=> Test more py3 versions

msal/application.py, tests/test_application.py
This is the equivalent of MSAL .Net's https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2888
=> Emit warning when common or organizations is used in acquire_token_for_client()

setup.py
This will close #473 , by leaving a trace on our due-diligence investigation.
=> Document our findings on addressing CVE-2022-29217

msal/authority.py
Add support for authority (STS) endpoint hosted on non-443 port.  This allows Azure CLI to use STS and Graph hosted on different endpoints.  e.g.
```
>  az cloud show -n DevEnv
{
"endpoints": {
"activeDirectory": "https://localhost:3001",
"activeDirectoryDataLakeResourceId": "https://datalake.azs/",
"activeDirectoryGraphResourceId": "https://localhost:3002/v1.0/",
"activeDirectoryResourceId": "https://login.azs",
...
},
"isActive": false,
"name": "DevEnv",
"profile": "latest",
"suffixes": {
...
}
}
```
This change will allow such configuration for Azure CLI and users can use az login to use it.
See https://github.com/Azure/azure-cli/issues/22553 for the error we get without this change.
=> Use provided authority port when building the tenant discovery endpoint

msal/application.py
We got it right in PR #358 based on the specs at that time, but we were using a fragile approach, which caused the "login.microsoft.com" being left out in subsequent PR #394.
Lesson learned. [Explicit is better than implicit](https://peps.python.org/pep-0020/)
=> Right regional endpoint for login.microsoft.com

.github/workflows/python-package.yml
This PR will change the test matrix to use the latest beta of Python 3.11 (currently b4) instead of alpha 5.
=> Test latest 3.11 beta

msal/application.py
MSAL PY already disables calls to AAD for ADFS-backed authority URIs, but missed the call for alias lookups. This call can only ever return an empty array or throw / crash the process if the public internet URL cannot be reached (as is the case in disconnected environments using a local ADFS identity solution). This fix skips that internet lookup and directly returns an empty array for ADFS authorities.
This fix is submitted to an experimental branch as MSAL PY will receive a larger design change later this year exposing configuration options which will include an explicit way to disable this alias lookup behavior. Because of that, this specific fix will **not** be directly included in any official MSAL PY releases as it is considered a behavioral change to disable this behavior without …
=> Disable authority alias lookup for ADFS-backed clouds

msal/application.py, msal/authority.py, tests/test_authority.py
Driven by [this conversation](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/492#pullrequestreview-1082931221), this PR implements `instance_discovery=False` based on [internal design 6504](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/6504). (Note: This PR does NOT contain `known_authority_hosts`, which was implemented in a different PR #492. The two features would co-exist when both PRs are merged in, but they can also work independently. Here they are implemented independently.)
As usual, the unit tests in this PR also serve as acceptance test for the aforementioned design.
=> Implement instance_discovery=False

msal/application.py, msal/authority.py, msal/broker.py, msal/token_cache.py, sample/interactive_sample.py, setup.py, tests/msaltest.py, tests/test_broker.py, tests/test_e2e.py
A broker is a component installed on your device. Broker implicitly gives your device an identity. By using a broker, your device becomes a factor that can satisfy MFA (Multi-factor authentication). This factor would become mandatory if/when a tenant's admin enables a corresponding Conditional Access (CA) policy. The broker's presence allows Microsoft identity platform to have higher confidence that the tokens are being issued to your device, and that is more secure. 
An additional benefit of broker is, it runs as a long-lived process with your device's OS, and maintains its own cache, so that your broker-enabled apps (even CLI) could automatically SSO from a previously established signed-in session.
Currently, broker is available on recent Windows platforms.
In this PR, MSAL Python …
=> Broker integration

msal/application.py, tests/test_e2e.py
On-hold. Do not merge until the [prerequisite internal work item](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/759642) is completed/deployed.
After merge, [this another internal work item](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2165938) will be closed.
=> Switch to new region endpoints

msal/token_cache.py
This is useful for App Service's managed identity.
=> Fallback to expires_on when expires_in is absent

msal/application.py
It is OK to also use PyMsalRuntime for SSH Cert now, since [ESTS has deployed the fix](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2060332).
=> Use broker for SSH Cert feature

msal/application.py, tests/test_application.py, tests/test_e2e.py
Before: MSAL Python will replace scope "client_id" with 'openid', 'profile', 'offline_access'.
After: MSAL Python will accept scope "client_id" and append 'openid', 'profile', 'offline_access' to it, before handling exclusions (if any). 
This PR will resolve #505. (Note that the new algorithm is `list((set(scopes) | {"profile", 'openid', 'offline_access'}) - <EXCLUDES>)`, which is slightly different than the last bullet point in [this conversation in #505](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/505#issuecomment-1285128365).
You can test this PR by `pip install --force-reinstall git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@allow-client_id-as-scope`.
=> Allow using client_id as scope. Needed by B2C.

README.md, docs/index.rst
Fixes a couple of broken links, update from https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-python-webapp to  https://learn.microsoft.com/en-us/azure/active-directory/develop/web-app-quickstart?pivots=devlang-python
=> Update reference to Python web app quickstart

setup.cfg
It'd be nice if pypi.org showed a link to the documentation. I think this is how it's specified, but all the docs these days show pyproject.toml, not setup.cfg, so I'm not positive.
See also https://github.com/rayluo/identity/pull/1
=> Update setup.cfg with documentation URL

msal/authority.py, tests/test_authority.py
The automation tests ~currently fail because~ passes:
* ~the new domain name is unavailable~
* ~the OIDC discovery endpoint is not available. When it is available, it is expected to also be in the ".../v2.0/..." endpoint.~
* ~we will continue the prototyping after the above two become available~
* ~Waiting on new lab api~
* New [lab api](https://msidlab.com/api/app/b8e9d222-c4ee-414c-ac29-b0eff1f32400) has been updated to return a new authority
Testers shall take a look into logs to double check your auth/token requests were sent out to `https://msidlabciam1.ciamlogin.com/d57fb3d4-4b5a-4144-9328-9c1f7d58179d/oauth2/v2.0/token?dc=ESTS-PUB-EUS-AZ1-FD000-TEST1` which was discovered from [OIDC discovery](https://msidlabciam1.ciamlogin.com/msidlabciam1.onmicrosoft.com/v2.0/.well-known/openid-co …
=> Supporting https://contoso.ciamlogin.com as authority

msal/authority.py
Our next MSAL Python release will be 1.22, so, the timing is right.
=> Remove a deprecated attribute, scheduled for 1.21+

msal/application.py
Although MSAL provides two top-level classes: PublicClientApplication and ConfidentialClientApplication, there is another less-popular but still-doable pattern which is to use the base class ClientApplication directly. So, that `allow_broker` is applicable to both PublicClientApplication and the base class ClientApplication. So, that dynamic check in base class is necessary.
The ConfidentialClientApplication inherits the `__init__()` and its documentation from base class. Now, we choose to add a sentence in that documentation to clarify that the parameter is not applicable to ConfidentialClientApplication.
See it in action in [the staged documentation](https://msal-python.readthedocs.io/en/docs-staging/#msal.ConfidentialClientApplication.params.allow_broker).
This resolves #544.
=> Clarify that allow_broker is not applicable to ConfidentialClientApplication

tests/test_e2e.py
Our lab switched to a new CIAM test tenant.
The two lab API were also updated:
1. [Get a test user and its test app from lab](https://msidlab.com/api/User?federationprovider=ciam&signInAudience=azureadmyorg&PublicClient=No) (Same API, different value in response)
2. [Get that app's authority and scope](https://msidlab.com/api/app/ced781e7-bdb0-4c99-855c-d3bacddea88a). Note: You shall NOT hardcode the test app's client id "ced7..." into your test case's source code or even configuration file. Instead, read it on-the-fly from the `appId` field from the response of the first API above. This way, in the future when/if the lab switch to a different client_id, your existing test automation will not break.
There is one change needed in the Confidential Client's test case. No more hardcoded …
=> Adjustment for new CIAM partition

msal/application.py, sample/confidential_client_certificate_sample.py, sample/confidential_client_secret_sample.py, tests/test_application.py, tests/test_e2e.py
Historically, MSAL Python's `acquire_token_silent(..., account=...)` has two usages:
1. it accepts a non-empty account to find token for that user. (This can be used in both `PublicClientApplication` and `ConfidentialClientApplication`.)
2. it also accepts account=None to find a token for the current app. (This is only used in combination with `ConfidentialClientApplication.acquire_token_for_client()`.)
Our existing documentations and samples (for example, [this one](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.22.0/sample/username_password_sample.py#L48-L52)) always put `#1`'s `acquire_token_silent(...)` call inside the `if accounts` clause, such that, when the account is None (i.e. the user signed out), the code path shall NOT accidentally attempt …
=> Remove acquire_token_silent(..., account=None) usage in a backward-compatible way

tests/test_e2e.py
Thanks @bgavrilMS for noticing the recent [alarm 13](https://github.com/AzureAD/microsoft-authentication-library-for-python/security/code-scanning/13) and [alarm 14](https://github.com/AzureAD/microsoft-authentication-library-for-python/security/code-scanning/14).
They are both false alarms. In this PR, we change the name of the variable.
The CodeQL has been configured to auto scan "PRs to dev" branch, so, a green test result would supposedly mean our fix is good. But then again, none of the [recent CodeQL action result](https://github.com/AzureAD/microsoft-authentication-library-for-python/actions/workflows/github-code-scanning/codeql) was red. So, we don't really know what the color means.
~P.S.: The current test automation failure is caused by a different reason. The msidlab8 seems …
=> Use a neutral name to hopefully avoid false alarm

tests/test_application.py
This simply renames a few tests.
=> Fix typo in test names (warnning → warning)

.github/workflows/python-package.yml, setup.cfg
It was already being tested, but 3.12 is GA now.
=> Mark package as supporting Python 3.12

msal/application.py, sample/confidential_client_certificate_sample.py, sample/confidential_client_secret_sample.py, sample/device_flow_sample.py, sample/interactive_sample.py, sample/username_password_sample.py, sample/vault_jwt_sample.py, tests/test_application.py
This will address #602 's first requirement. The successful token acquisition result will have a new key `token_source` whose value will be `idp`, `cache` or `broker`.
Existing unit test cases have been updated to test this new behavior.
=> Expose token_source for observability

msal/__main__.py, msal/application.py, sample/interactive_sample.py, tests/test_e2e.py
This PR deprecates the old `ClientApplication.__init__(..., allow_broker=True)`. Please use `PublicClientApplication.__init__(..., enable_broker_on_windows=True)` instead.
This change is the first step for us to moving to per-platform opt-in flag.
This PR will also close #510 , because we no longer go with that direction.
@jiasli , @xiangyan99,
* You do not have to immediately make a dependency on this change, but you are still recommended to expose the per-platform opt-in flag in your code base accordingly
* Please run your smoke test with this PR, as it will likely become the last change in an upcoming MSAL Python 1.25
=> Deprecate allow_broker, use enable_broker_on_windows

msal/__main__.py, msal/application.py, msal/broker.py, msal/token_cache.py, tests/test_account_source.py
This is useful when the user somehow chose to use device code flow successfully and now want to do an acquire_token_silent(). The event sequence in this scenario looks like this:
1. End user enabled broker.
2. For whatever reason, end user chooses to sign in using Device Code Flow (DCF). Broker (WAM) does not support DCF but, per our existing design, we do not want to break this scenario, so MSAL automatically falls back to use native DCF implementation. This is already happening today, and the sign-in would be successful, and access token (AT) and refresh token (RT) will be stored inside MSAL's native token cache.
3. Subsequent AcquireTokenSilent() call (especially those after the initial access token expires) would attempt broker code path, and end up with an "account not found" error …
=> acquire_token_silent() shall not invoke broker if the account was not established by broker

msal/application.py
* Deprecation: `allow_broker` will be replaced by `enable_broker_on_windows` (#613)
* Bugfix: Device Code Flow (and Username Password Flow) and its subsequent silent request will automatically bypass broker and succeed. (#569)
* Enhancement: `acquire_token_interactive()` supports running inside Docker
* Observability: Successful token response will contain a new `token_source` field to indicate where the token was obtained from: `identity_provider`, `cache` or `broker`. (#610)
=> Release 1.25.0

setup.cfg
When trying to build wheel it gives warning
```
writing msal.egg-info/PKG-INFO
/usr/lib/python3.11/site-packages/setuptools/dist.py:173: SetuptoolsDeprecationWarning: Invalid config.
!!
********************************************************************************
newlines are not allowed in `summary` and will break in the future
********************************************************************************
!!
write_field('Summary', single_line(summary))
```
This can be seen in latest wheel on pypi `msal-1.25.0-py2.py3-none-any.whl`
summary field in METADATA file is incomplete, it only states:
`Summary: The Microsoft Authentication Library (MSAL) for Python library`
=> Remove newlines from description / Fix summary.

msal/application.py
@rayluo - I didn't find any unit tests related to region auto-discovery. Happy to add one if I missed it.
=> #629 - skip region discory when region=None

msal/__init__.py, msal/__main__.py, msal/application.py, msal/auth_scheme.py, msal/broker.py, tests/test_e2e.py
This is the implementation of the [internal work item](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1791492), and [this internal design doc](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/PoPTokensProtocol/PoP_API_In_MSAL.md&_a=preview).
Currently, this PR provides a low level API to obtain a Proof-of-Possesson (PoP) access token.
We may add more end-to-end test case in the future. And we may provide a high-level API.
The beta preview of this feature is available by `pip install --ignore-installed git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@pop`
=> AT POP for Public Client based on broker

msal/__init__.py, msal/__main__.py, msal/application.py, msal/auth_scheme.py, msal/broker.py, tests/test_e2e.py
* Do not auto-detect region if app developer does not opt-in to region (#629, #630)
* Support Proof-of-Possession (PoP) for Public Client based on broker (#511)
=> Release 1.26.0

msal/application.py, msal/token_cache.py, tests/test_token_cache.py
This PR currently contains 2 commits.
1. The first commit orders scopes on save, which is similar to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4479. Existing unit tests need adjustment to match the changed scope order.
2. The second commit optimizes the happy path of access token read, which was the idea mentioned in [this conversation](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4479#discussion_r1437466906). Basically, when searching for an access token, this PR uses the token key to attempt an O(1) search, and falls back to O(n) search when necessary.
* No other unit test adjustment is needed, meaning this change is backward compatible.
* Existing benchmark test shows ~40% speed improvement on "token cache hit" code path, …
=> Order scopes on save, and optimize the happy path for access token read

msal/application.py
This change is inspired by [this conversation](https://github.com/Azure/azure-cli/issues/20231#issuecomment-1887956233).
CC: @jiasli
=> Attempts account removal from broker first

sample/confidential_client_certificate_sample.py, sample/confidential_client_secret_sample.py, sample/device_flow_sample.py, sample/interactive_sample.py, sample/migrate_rt.py, sample/username_password_sample.py, sample/vault_jwt_sample.py
=> Give a hint on where the client_id came from

msal/application.py, tests/test_application.py
Based on [this understanding](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/650#issuecomment-1935768909), here comes this ([evil?](https://en.wikipedia.org/wiki/Number_of_the_beast)) PR, which will resolve #640 and resolve #650
=> Implement remove_tokens_for_client()

msal/mex.py
Using a bare except statement when importing hides other errors, which then get lost when the next import fails.
=> Don't use bare except when importing

msal/broker.py
MSAL.cpp fixed the URI parsing logic to not allow invalid URIs which causes the default redirect URI to not be properly set when calling MSAL.runtime. This caused the sev2 ICM with azcli.
Chaning the default to be the default RU for native clients: https://login.microsoftonline.com/common/oauth2/nativeclient
=> Update the default broker redirect URI to be a valid URI

msal/application.py, setup.cfg, tests/broker-test.py
* New feature: `PublicClientApplication` and `ConfidentialClientApplication` have a new `oidc_authority` parameter that can be used to specify authority of any generic OpenID Connect authority, typically the customized domain for CIAM. (#676, #678)
* Dropping Python 2.7
=> MSAL Python 1.28.0

docs/index.rst, msal/__init__.py, msal/application.py, msal/managed_identity.py, msal/throttled_http_client.py, sample/.env.sample.managed_identity, sample/managed_identity_sample.py, tests/test_mi.py, tests/test_throttled_http_client.py
Note: This is a proof-of-concept, which means there is no guarantee that this behavior will be eventually included into MSAL Python.
There are two new APIs added.
* ~The high level API works for your confidential client which federated with a managed identity.~ This will be moved into a separated PR for its own consideration.
```python
import msal
cca = msal.ConfidentialClientApplication(
"my_client_id",
client_credential=msal.SystemAssignedManagedIdentity(),  # Or it can be an msal.UserAssignedManagedIdentity(client_id="guid")
...)
result = cca.acquire_token_for_client(scopes["scope1", "scope2"])  # It uses scopes
```
* The low level API acquires token for managed identity
```python
import msal, requests
mi = msal.ManagedIdentityClient(
msal.SystemAssignedManagedIdentity(),  # Or it can …
```
=> Managed Identity for Azure VM, App Service, Service Fabric, etc.

tests/test_e2e.py
* There is no code change to MSAL's implementation in this PR. This means the existing MSAL Python needs no change to support the OBO-for-SP scenario, perhaps since the initial OBO implementation.
* This PR contains changes to MSAL's test case, to demonstrate that how OBO for SP could work. It is a matter of how the mid-tier app chooses to manage the potentially-more-than-one SP "accounts", which can be an open topic for discussion.
* Currently, the test certificate is *not* committed, so, the new test case will not be run in CI. But it was manually run by PR author.
=> Add test case to show that OBO supports SP
