msal/wstrust_request.py

Porting ADAL Python PR 194 (https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/194)

Remove inaccurate RE which came from ADAL Python

---

msal/application.py
msal/wstrust_response.py

This PR implements same behavior as we did in [ADAL Python PR 187](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/187)

Adding SAML 1.1 token types

---

msal/application.py

Merge the release 0.2.0 branch back to dev branch.

MSAL Python 0.2.0

---

msal/application.py

Merge the release 0.3.0 branch back to dev branch.

MSAL Python 0.3.0

---

msal/application.py

Merge release branch back to dev

MSAL Python 0.4.0

---

msal/authority.py

Updating authority URL regexp to have escaped backslash

---

setup.py

Adding the XML tests files so the tests can be run from a conda build

Exclude tests and add license file to pip package

---

msal/application.py

Merge the release 0.6.0 branch back to dev branch.

MSAL Python 0.6.0

---

sample/username_password_sample.py

Update username_password_sample.py to fix issue 97

---

msal/application.py

That release also closes #115.

Merge 0.9.0 release back to dev branch

---

tests/test_e2e.py

Old lab API is retiring. We switch to new lap api in this PR.
This PR will close #108

Change to new lab api

---

tests/test_e2e.py

With these test cases, we will be able to address #132

ADFS 2019 on-prem test cases

---

msal/application.py

This PR closes #57, closes, #130, closes #132.

Merge MSAL Python 1.1.0 back to dev branch

---

msal/application.py

Merge MSAL Python 1.2.0 back to dev branch

---

README.md

Because, why not? :-)
By the way, according to this [data source](https://pypistats.org/packages/msal), the number of downloads (whatever that means) roughly grow 10x in last 6 months.

Add a download badge into README

---

msal/application.py

Improve SNI docs based on https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/225
CC: @mbearup

Improve SNI docs

---

msal/application.py

Migration should fail gracefully even on wrong RT

---

msal/wstrust_request.py

Changing case of messageID in WS-Trust request document

---

tests/test_authority.py

Thanks Abhi for all the hard work leading to this adjustment! This fixes #211

Ensure no side effect leaks outside

---

msal/application.py
msal/authority.py

Fetching device code endpoint from discovery

---

msal/application.py
tests/test_application.py

<sub>Linking back to relevant issue (on behalf of Abhi ^_^) for easier cross-check during reviewing</sub> This will close #174

Client capabilities

---

msal/application.py

Merge MSAL Python 1.5.1 back to dev branch

---

msal/application.py

Bump version number, and document the version of new API

Merge MSAL Python 1.6.0 back to dev branch

---

sample/interactive_sample.py

Demonstrate how to use the new `acquire_token_interactive()` API introduced by #260

A sample for the new acquire_token_interactive()

---

msal/application.py

Merge MSAL Python 1.7.0 back to dev

---

msal/oauth2cli/authcode.py

Chanbge acquire_token_interactive to lazy import webbrowser

---

msal/application.py

Merge MSAL 1.8.0 back to dev branch

---

msal/application.py

After a recent Q&A conversation, this is the outcome to improve our doc. #Supportability

Documents Redirect URI requirement for interactive flow

---

.github/workflows/python-package.yml

Only trigger CI/CD when a PR is labelled

---

msal/application.py

Merge Release 1.11.0 back to dev branch

---

msal/token_cache.py

This PR fixes #362. We will cut a new release shortly after this PR got merged.

Also redact id token from now on

---

msal/oauth2cli/oidc.py

Address [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/449/files#r784538246) by @jiasli .

Time suggestion

---

msal/application.py

(The MSAL Python 1.18.0b1 has been stable in last 2 weeks, and we are now shipping it as 1.18.0)
* New feature: Optional `initiate_auth_code_flow(..., response_mode="form_post")` to allow the auth code being delivered to your app by form post, which is considered even more secure. (#396, #469)
* New feature: `acquire_token_interactive(..., prompt="none")` can obtain some tokens from within Cloud Shell, without any prompt. (#420)

Release 1.18.0

---

msal/oauth2cli/assertion.py

I stumbled upon this typo while investigating a different issue in this file.

Fix typo in code

---

docs/index.rst

Inspired by some customers' feedback.

Clarify when (not) to read API section

---

msal/application.py

Assuming the answer to [this question](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4167#issuecomment-1736303602) is a yes, this PR is the equivalent of [this MSAL .Net PR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4337). Manually tested.

Remove x-client-cpu

---

msal/application.py
sample/confidential_client_certificate_sample.py
sample/confidential_client_secret_sample.py
sample/device_flow_sample.py
sample/interactive_sample.py
sample/username_password_sample.py
sample/vault_jwt_sample.py

This PR addresses the part of #602 .
This is currently a draft but still ready for review. I'll update this PR to modify more samples, probably including PCA samples.

Demonstrate how to use global token cache
